"""add_avatar_url_and_attachments

Revision ID: 07ecb8d43f5d
Revises: dd86c9e3a981
Create Date: 2026-07-21 20:31:12.321768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ecb8d43f5d'
down_revision: Union[str, Sequence[str], None] = 'dd86c9e3a981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('reviews', 'attachments')
    # ### end Alembic commands ###
