"""add order item batch tracking

Revision ID: 140493a37321
Revises: c556c1e9a4ec
Create Date: 2026-06-11 09:03:45.550925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140493a37321'
down_revision: Union[str, Sequence[str], None] = 'c556c1e9a4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_batches',
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_batches_id'), 'order_item_batches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_batches_id'), table_name='order_item_batches')
    op.drop_table('order_item_batches')
    # ### end Alembic commands ###
