"""add active_skill to conversations

Revision ID: 3174dd71df7a
Revises: dd86c9e3a981
Create Date: 2026-07-22 11:10:52.436705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3174dd71df7a'
down_revision: Union[str, Sequence[str], None] = 'dd86c9e3a981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('active_skill', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'active_skill')
    # ### end Alembic commands ###
