"""add store category table

Revision ID: 568ad518d404
Revises: 7efc19dacc2b
Create Date: 2026-07-15 19:53:41.723790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568ad518d404'
down_revision: Union[str, Sequence[str], None] = '7efc19dacc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_store_categories_id'), 'store_categories', ['id'], unique=False)
    op.add_column('stores', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'stores', 'store_categories', ['category_id'], ['id'], ondelete='SET NULL')

    # Seed default categories and migrate existing stores
    import uuid
    bind = op.get_bind()
    
    default_categories = ["Bakery", "Resto", "Cafe", "Supermarket", "Catering", "Lainnya"]
    category_map = {}
    
    for cat_name in default_categories:
        cat_id = uuid.uuid4()
        bind.execute(
            sa.text(
                "INSERT INTO store_categories (id, name, created_at) "
                "VALUES (:id, :name, NOW()) "
                "ON CONFLICT (name) DO NOTHING"
            ),
            {"id": cat_id, "name": cat_name}
        )
        
    result = bind.execute(sa.text("SELECT id, name FROM store_categories"))
    for row in result.all():
        category_map[row.name.lower()] = row.id

    stores_result = bind.execute(sa.text("SELECT id, category FROM stores"))
    for store in stores_result.all():
        store_id = store.id
        old_cat = store.category
        
        if not old_cat:
            target_cat_name = "Lainnya"
        else:
            target_cat_name = old_cat.strip()
            
        target_key = target_cat_name.lower()
        if target_key not in category_map:
            new_cat_id = uuid.uuid4()
            bind.execute(
                sa.text("INSERT INTO store_categories (id, name, created_at) VALUES (:id, :name, NOW())"),
                {"id": new_cat_id, "name": target_cat_name}
            )
            category_map[target_key] = new_cat_id
            
        bind.execute(
            sa.text("UPDATE stores SET category_id = :category_id WHERE id = :id"),
            {"category_id": category_map[target_key], "id": store_id}
        )

    op.drop_column('stores', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Restore category strings from store_categories relation
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "UPDATE stores s "
            "SET category = c.name "
            "FROM store_categories c "
            "WHERE s.category_id = c.id"
        )
    )
    
    op.drop_constraint('stores_category_id_fkey', 'stores', type_='foreignkey')
    op.drop_column('stores', 'category_id')
    op.drop_index(op.f('ix_store_categories_id'), table_name='store_categories')
    op.drop_table('store_categories')
    # ### end Alembic commands ###
