"""Add profile columns to business

Revision ID: 577ee817bdac
Revises: 7337a875dc94
Create Date: 2026-07-20 20:57:04.819373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577ee817bdac'
down_revision: Union[str, Sequence[str], None] = '7337a875dc94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('address', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('legal_entity', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('pic', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('sdg_commitment', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('year_founded', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('businesses', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'website')
    op.drop_column('businesses', 'description')
    op.drop_column('businesses', 'logo_url')
    op.drop_column('businesses', 'year_founded')
    op.drop_column('businesses', 'sdg_commitment')
    op.drop_column('businesses', 'pic')
    op.drop_column('businesses', 'legal_entity')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###
