"""add_hq_wallet_support_to_wallets

Revision ID: 7337a875dc94
Revises: a6e5e388f7d0
Create Date: 2026-07-20 11:38:21.121873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7337a875dc94'
down_revision: Union[str, Sequence[str], None] = 'a6e5e388f7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE wallettype ADD VALUE IF NOT EXISTS 'HQ'")
    op.execute("ALTER TYPE wallettype ADD VALUE IF NOT EXISTS 'hq'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_BRANCH_DEPOSIT'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_INVESTMENT'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_SPONSORSHIP'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_IT_INFRA'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_NATIONAL_MARKETING'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'CAT_OFFICE_OPS'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catBranchDeposit'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catInvestment'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catSponsorship'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catItInfra'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catNationalMarketing'")
    op.execute("ALTER TYPE wallettransactioncategory ADD VALUE IF NOT EXISTS 'catOfficeOps'")

    # ### commands auto generated by Alembic - please adjust! ###


    op.create_index('idx_inv_batch_store_prod_exp', 'inventory_batches', ['store_id', 'product_id', 'expired_at'], unique=False)
    op.create_index('idx_inv_tx_store_prod_created', 'inventory_transactions', ['store_id', 'product_id', 'created_at'], unique=False)
    op.create_index('idx_order_store_status_created', 'orders', ['store_id', 'status', 'created_at'], unique=False)
    op.alter_column('products', 'supplier_lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.create_index('idx_product_store_published', 'products', ['store_id', 'is_published'], unique=False)
    op.create_index('idx_tx_store_status', 'transactions', ['store_id', 'status'], unique=False)
    op.create_index('idx_wtx_wallet_date', 'wallet_transactions', ['wallet_id', 'transaction_date'], unique=False)
    op.add_column('wallets', sa.Column('business_id', sa.Uuid(), nullable=True))
    op.alter_column('wallets', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_business_wallet_type', 'wallets', ['business_id', 'type'])
    op.create_foreign_key(None, 'wallets', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_constraint('uq_business_wallet_type', 'wallets', type_='unique')
    op.alter_column('wallets', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('wallets', 'business_id')
    op.drop_index('idx_wtx_wallet_date', table_name='wallet_transactions')
    op.drop_index('idx_tx_store_status', table_name='transactions')
    op.drop_index('idx_product_store_published', table_name='products')
    op.alter_column('products', 'supplier_lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.drop_index('idx_order_store_status_created', table_name='orders')
    op.drop_index('idx_inv_tx_store_prod_created', table_name='inventory_transactions')
    op.drop_index('idx_inv_batch_store_prod_exp', table_name='inventory_batches')
    # ### end Alembic commands ###
