"""create_cart_reservations_table

Revision ID: 8e63ae99cefc
Revises: b34c94940e16
Create Date: 2026-07-23 00:28:21.081794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e63ae99cefc'
down_revision: Union[str, Sequence[str], None] = 'b34c94940e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'cart_reservations' not in tables:
        op.create_table('cart_reservations',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('product_id', sa.Uuid(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_cart_res_expires', 'cart_reservations', ['expires_at'], unique=False)
        op.create_index('idx_cart_res_user_product', 'cart_reservations', ['user_id', 'product_id'], unique=False)
        op.create_index(op.f('ix_cart_reservations_id'), 'cart_reservations', ['id'], unique=False)
        op.create_index(op.f('ix_cart_reservations_product_id'), 'cart_reservations', ['product_id'], unique=False)
        op.create_index(op.f('ix_cart_reservations_user_id'), 'cart_reservations', ['user_id'], unique=False)
        
    if 'order_escrows' in tables:
        op.alter_column('order_escrows', 'created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('now()'))
        op.alter_column('order_escrows', 'updated_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   nullable=False,
                   existing_server_default=sa.text('now()'))
        
        indexes = [idx['name'] for idx in inspector.get_indexes('order_escrows')]
        if 'ix_order_escrows_id' not in indexes:
            op.create_index(op.f('ix_order_escrows_id'), 'order_escrows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_escrows_id'), table_name='order_escrows')
    op.alter_column('order_escrows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_escrows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cart_reservations_user_id'), table_name='cart_reservations')
    op.drop_index(op.f('ix_cart_reservations_product_id'), table_name='cart_reservations')
    op.drop_index(op.f('ix_cart_reservations_id'), table_name='cart_reservations')
    op.drop_index('idx_cart_res_user_product', table_name='cart_reservations')
    op.drop_index('idx_cart_res_expires', table_name='cart_reservations')
    op.drop_table('cart_reservations')
    # ### end Alembic commands ###
