"""fix remaining missing columns

Revision ID: 9845f3736445
Revises: 568ad518d404
Create Date: 2026-07-15 20:33:42.309031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9845f3736445'
down_revision: Union[str, Sequence[str], None] = '568ad518d404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_batches', sa.Column('surplus_starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inventory_batches', sa.Column('batch_tag', sa.String(), nullable=True))
    op.drop_column('inventory_batches', 'available_from')
    op.add_column('inventory_transactions', sa.Column('reason', sa.String(), nullable=False))
    op.add_column('inventory_transactions', sa.Column('reference', sa.String(), nullable=True))
    op.alter_column('products', 'product_type',
               existing_type=postgresql.ENUM('READY_TO_EAT', 'PACKAGED', 'BAKERY', 'PRODUCE', 'OTHER', name='producttype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'product_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('READY_TO_EAT', 'PACKAGED', 'BAKERY', 'PRODUCE', 'OTHER', name='producttype'),
               existing_nullable=False)
    op.drop_column('inventory_transactions', 'reference')
    op.drop_column('inventory_transactions', 'reason')
    op.add_column('inventory_batches', sa.Column('available_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('inventory_batches', 'batch_tag')
    op.drop_column('inventory_batches', 'surplus_starts_at')
    # ### end Alembic commands ###
