"""support_multiple_wallets_and_payouts

Revision ID: a6e5e388f7d0
Revises: 9845f3736445
Create Date: 2026-07-16 19:20:34.623959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e5e388f7d0'
down_revision: Union[str, Sequence[str], None] = '9845f3736445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    # Manually create new ENUM types in PostgreSQL
    wallet_transaction_category_enum = postgresql.ENUM('CAT_SALES', 'CAT_CAPITAL', 'CAT_ADJUSTMENT', 'CAT_INGREDIENTS', 'CAT_SALARY', 'CAT_UTILITIES', 'CAT_RENT', 'CAT_LOGISTICS', 'CAT_MARKETING', 'CAT_MAINTENANCE', 'CAT_WITHDRAWAL', 'CAT_OTHERS', name='wallettransactioncategory')
    wallet_transaction_category_enum.create(op.get_bind(), checkfirst=True)
    
    wallet_type_enum = postgresql.ENUM('DIGITAL', 'OFFLINE', name='wallettype')
    wallet_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('withdrawal_requests',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('account_holder', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='transactionstatus', create_type=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_id'), 'withdrawal_requests', ['id'], unique=False)
    op.add_column('transactions', sa.Column('payment_details', sa.JSON(), nullable=True))
    op.add_column('wallet_transactions', sa.Column('withdrawal_request_id', sa.Uuid(), nullable=True))
    
    # Category and transaction_date added as nullable first
    op.add_column('wallet_transactions', sa.Column('category', sa.Enum('CAT_SALES', 'CAT_CAPITAL', 'CAT_ADJUSTMENT', 'CAT_INGREDIENTS', 'CAT_SALARY', 'CAT_UTILITIES', 'CAT_RENT', 'CAT_LOGISTICS', 'CAT_MARKETING', 'CAT_MAINTENANCE', 'CAT_WITHDRAWAL', 'CAT_OTHERS', name='wallettransactioncategory'), nullable=True))
    op.add_column('wallet_transactions', sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'wallet_transactions', 'withdrawal_requests', ['withdrawal_request_id'], ['id'], ondelete='SET NULL')
    
    # Populate existing transaction categories and dates
    op.execute("UPDATE wallet_transactions SET category = 'CAT_SALES' WHERE type = 'CREDIT'")
    op.execute("UPDATE wallet_transactions SET category = 'CAT_OTHERS' WHERE type != 'CREDIT'")
    op.execute("UPDATE wallet_transactions SET transaction_date = created_at")
    
    # Alter columns to NOT NULL
    op.alter_column('wallet_transactions', 'category', nullable=False)
    op.alter_column('wallet_transactions', 'transaction_date', nullable=False)

    # Wallet type added as nullable first
    op.add_column('wallets', sa.Column('type', sa.Enum('DIGITAL', 'OFFLINE', name='wallettype'), nullable=True))
    op.add_column('wallets', sa.Column('saved_bank_info', sa.JSON(), nullable=True))
    
    # Populate existing wallet types as 'DIGITAL'
    op.execute("UPDATE wallets SET type = 'DIGITAL'")
    
    # Alter type to NOT NULL
    op.alter_column('wallets', 'type', nullable=False)

    op.drop_constraint('wallets_store_id_key', 'wallets', type_='unique')
    op.create_unique_constraint('uq_store_wallet_type', 'wallets', ['store_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_store_wallet_type', 'wallets', type_='unique')
    op.create_unique_constraint('wallets_store_id_key', 'wallets', ['store_id'])
    op.drop_column('wallets', 'saved_bank_info')
    op.drop_column('wallets', 'type')
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_column('wallet_transactions', 'transaction_date')
    op.drop_column('wallet_transactions', 'category')
    op.drop_column('wallet_transactions', 'withdrawal_request_id')
    op.drop_column('transactions', 'payment_details')
    op.drop_index(op.f('ix_withdrawal_requests_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    
    # Drop manually created custom PG Enum types
    op.execute("DROP TYPE IF EXISTS wallettype")
    op.execute("DROP TYPE IF EXISTS wallettransactioncategory")
    # ### end Alembic commands ###
