"""add default_latitude and default_longitude to users

Revision ID: b4f6d4b7314d
Revises: bf011b175044
Create Date: 2026-07-23 10:51:46.513102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f6d4b7314d'
down_revision: Union[str, Sequence[str], None] = 'bf011b175044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('default_longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_longitude')
    op.drop_column('users', 'default_latitude')
    # ### end Alembic commands ###
