"""create log system table

Revision ID: bf011b175044
Revises: de8a60afd0d7
Create Date: 2026-07-23 09:53:36.979635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf011b175044'
down_revision: Union[str, Sequence[str], None] = 'de8a60afd0d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_systems',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_systems_id'), 'log_systems', ['id'], unique=False)
    op.create_index(op.f('ix_log_systems_platform'), 'log_systems', ['platform'], unique=False)
    op.create_index(op.f('ix_log_systems_severity'), 'log_systems', ['severity'], unique=False)
    op.create_index(op.f('ix_log_systems_user_email'), 'log_systems', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_systems_user_email'), table_name='log_systems')
    op.drop_index(op.f('ix_log_systems_severity'), table_name='log_systems')
    op.drop_index(op.f('ix_log_systems_platform'), table_name='log_systems')
    op.drop_index(op.f('ix_log_systems_id'), table_name='log_systems')
    op.drop_table('log_systems')
    # ### end Alembic commands ###
