"""add store_id to user

Revision ID: c14ab2a129ef
Revises: 140493a37321
Create Date: 2026-06-11 21:28:43.291668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14ab2a129ef'
down_revision: Union[str, Sequence[str], None] = '140493a37321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('store_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'store_id')
    # ### end Alembic commands ###
