"""add_store_category_and_pickup_time

Revision ID: d299cac51306
Revises: bd04fac638f5
Create Date: 2026-07-03 12:41:45.466977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd299cac51306'
down_revision: Union[str, Sequence[str], None] = 'bd04fac638f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('category', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('pickup_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'pickup_time')
    op.drop_column('stores', 'category')
    # ### end Alembic commands ###
