"""add_image_url_expiry_time_available_from

Revision ID: ddcbc413838c
Revises: d299cac51306
Create Date: 2026-07-03 15:26:38.513710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcbc413838c'
down_revision: Union[str, Sequence[str], None] = 'd299cac51306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_batches', sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('expiry_time', sa.Integer(), server_default='24', nullable=False))
    op.add_column('stores', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'image_url')
    op.drop_column('products', 'expiry_time')
    op.drop_column('products', 'image_url')
    op.drop_column('inventory_batches', 'available_from')
    # ### end Alembic commands ###
